image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      touch /tmp/.npm-lock
      cd src/
      npm install
      rm /tmp/.npm-lock
    command: |
      cd src/
      npm run start
  - init: sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
    command: |
      hugo server \
        --baseUrl $(gp url 1313) \
        --appendPort=false \
        --source "./exampleSite" \
        --destination "../public" \
        --themesDir "../.." \
        --verbose
ports:
  - port: 1313
    onOpen: open-preview
