name = "crafty-theme"
description = "Clean hand-crafted theme for Hugo."
homepage = "https://crafty-theme.willcraft.software"
tags = [
  "company",
  "blog",
]
features = [
  "comments",
]
license = "MIT"
licenselink = "https://github.com/wewillcraft/crafty-theme/blob/master/LICENSE.md"
min_version = "0.41.0"

[author]
  name = "We Will Craft"
  homepage = "https://willcraft.software/"
