name = "crafty"
description = "Clean hand-crafted theme for Hugo."
homepage = "https://github.com/wewillcraft/gohugo-theme-crafty/"

tags = ["company", "blog"]
features = []

license = "MIT"
licenselink = "https://github.com/wewillcraft/gohugo-theme-crafty/blob/master/LICENSE.md"

min_version = "0.41.0"

[author]
  name = "We Will Craft"
  homepage = "https://willcraft.software/"
