name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.3"

      - name: Build
        run: |
          HUGO_ENV=production hugo --minify \
            --baseURL "https://crafty-theme.willcraft.software" \
            --source "./exampleSite" \
            --destination "../public" \
            --themesDir "../.." \
            --verbose

      - name: Add CNAME
        run: echo "crafty-theme.willcraft.software" > public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.CRAFTY_THEME_PAGES_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: false
          allow_empty_commit: true
